;THIS FILE IS AUTOMATICALLY GENERATED BY BRIV GEM FARM PERFORMANCE ADDON
#include *i %A_LineFile%\..\..\IC_BrivGemFarm_LevelUp_Extra\IC_BrivGemFarm_LevelUp_Addon.ahk
#include *i %A_LineFile%\..\..\IC_RNGWaitingRoom_Extra\IC_RNGWaitingRoom_Addon.ahk
#include *i %A_LineFile%\..\..\IC_GameSettingsFix_Extra\IC_GameSettingsFix_Addon.ahk
#include *i %A_LineFile%\..\..\IC_ClaimDailyPlatinum_Extra\IC_ClaimDailyPlatinum_Addon.ahk
